# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='users',
        ),
        migrations.AddField(
            model_name='events',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
